"""Add password_hash field

Revision ID: 86259ce87a3c
Revises: 
Create Date: 2025-02-05 21:33:43.372153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86259ce87a3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=120), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
